apiVersion: apps/v1
kind: Deployment
metadata:
  name:  nginx
  namespace: staging
spec:
  selector:
  replicas: 2
  strategy:
  template:
    spec:
      containers:
      - name:  nginx
        image:  nginx:1.25.1-alpine